version: "3.8"

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    restart: unless-stopped
    user: root
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    #password: root123

  nestipy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestipy
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/nestipy
    command: [ "nestipy", "start", "--dev" ]