global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'nestipy'
    scrape_interval: 5s
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['nestipy:8000']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']