from __future__ import annotations

from typing import Any, Callable, Protocol

from nestipy.common.template import TemplateEngine


class HttpAdapterLike(Protocol):
    """Protocol describing the HTTP adapter surface used by core helpers."""

    debug: bool

    def set(self, key: str, value: Any) -> None: ...
    def get_state(self, key: str) -> Any: ...
    def get_template_engine(self) -> TemplateEngine | None: ...
    def create_wichard(self, base: str = "", name: str = "path") -> str: ...
    def get(self, path: str, handler: Callable, meta: dict | None = None) -> None: ...
    def head(self, path: str, handler: Callable, meta: dict | None = None) -> None: ...
    def all(self, path: str, handler: Callable, meta: dict | None = None) -> None: ...
    def static(self, path: str, directory: str, *args, **kwargs) -> None: ...
    def get_io_adapter(self) -> Any: ...
    def enable_cors(self) -> None: ...
    def add_global_interceptors(self, *interceptors: Any) -> None: ...
    def add_global_filters(self, *filters: Any) -> None: ...
    def add_global_guards(self, *guards: Any) -> None: ...
    def add_global_pipes(self, *pipes: Any) -> None: ...
