"""Type exports for nestipy.web."""

from __future__ import annotations

from typing import Any

from .actions import (
    ActionAuth,
    ActionContext,
    ActionGuard,
    ActionNonceCache,
    ActionPermissionGuard,
    ActionPermissions,
    ActionsModule,
    ActionsOption,
    ActionSignatureGuard,
    CsrfActionGuard,
    OriginActionGuard,
    UseActionGuards,
    action,
)
from .actions_client import (
    build_action_specs,
    build_actions_schema,
    codegen_actions_from_url,
    generate_actions_client_code,
    generate_actions_client_code_from_schema,
    write_actions_client_file,
)
from .client import codegen_client, codegen_client_from_url
from .compiler import CompilerError, build_routes, compile_app
from .config import WebConfig
from .ui import (
    Fragment,
    Slot,
    component,
    create_context,
    external,
    external_fn,
    h,
    js,
    new_,
    props,
    use_callback,
    use_context,
    use_effect,
    use_effect_async,
    use_memo,
    use_ref,
    use_state,
)

__all__: list[str] = [
    "ActionAuth",
    "ActionContext",
    "ActionGuard",
    "ActionNonceCache",
    "ActionPermissionGuard",
    "ActionPermissions",
    "ActionsModule",
    "ActionsOption",
    "ActionSignatureGuard",
    "CsrfActionGuard",
    "OriginActionGuard",
    "UseActionGuards",
    "action",
    "build_action_specs",
    "build_actions_schema",
    "codegen_actions_from_url",
    "generate_actions_client_code",
    "generate_actions_client_code_from_schema",
    "write_actions_client_file",
    "codegen_client",
    "codegen_client_from_url",
    "CompilerError",
    "build_routes",
    "compile_app",
    "WebConfig",
    "Fragment",
    "Slot",
    "component",
    "create_context",
    "external",
    "external_fn",
    "h",
    "js",
    "new_",
    "props",
    "use_callback",
    "use_context",
    "use_effect",
    "use_effect_async",
    "use_memo",
    "use_ref",
    "use_state",
]
