from __future__ import annotations

from typing import Any, Callable, Iterable, Protocol, TypedDict, TypeVar
from typing import Final, NotRequired, Unpack

COMPONENT_MARK_ATTR: Final[str]
COMPONENT_NAME_ATTR: Final[str]
PROPS_MARK_ATTR: Final[str]

class ExternalComponent:
    module: str
    name: str
    default: bool
    alias: str | None
    @property
    def import_name(self) -> str: ...
    def __call__(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...

class JSExpr(str): ...

class LocalComponent:
    name: str
    def __call__(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...

class Node:
    tag: Any
    props: dict[str, Any]
    children: list[Any]

class _Fragment: ...
class _Slot: ...
Fragment: _Fragment
Slot: _Slot

def js(expr: str) -> JSExpr: ...
def external(module: str, name: str, *, default: bool = False, alias: str | None = None) -> ExternalComponent: ...
def component(fn: Callable[..., Any]) -> Callable[..., Any]: ...
def props(cls: type) -> type: ...
def use_state(initial: Any = ...) -> tuple[Any, Any]: ...
def use_effect(effect: Any, deps: Any | None = ...) -> None: ...
def use_memo(factory: Any, deps: Any | None = ...) -> Any: ...
def use_callback(callback: Any, deps: Any | None = ...) -> Any: ...
def use_context(context: Any) -> Any: ...
def use_ref(initial: Any = ...) -> Any: ...
def create_context(default: Any = ...) -> Any: ...

class HTMLProps(TypedDict, total=False):
    id: str
    class_name: str
    class_: str
    data_: dict[str, Any]
    aria_: dict[str, Any]
    title: str
    style: str | dict[str, Any]
    role: str
    tab_index: int
    hidden: bool
    disabled: bool
    checked: bool
    selected: bool
    read_only: bool
    multiple: bool
    required: bool
    value: Any
    name: str
    type: str
    placeholder: str
    href: str
    target: str
    rel: str
    src: str
    alt: str
    width: int | str
    height: int | str
    rows: int
    cols: int
    col_span: int
    row_span: int
    min: int | float | str
    max: int | float | str
    min_length: int
    max_length: int
    pattern: str
    step: int | float | str
    for_: str
    http_equiv: str
    accept_charset: str
    accept: str
    capture: str
    content: str
    method: str
    action: str
    enc_type: str
    no_validate: bool
    form: str
    list: str
    size: int
    wrap: str
    auto_complete: str
    auto_focus: bool
    download: str | bool
    draggable: bool
    spell_check: bool
    content_editable: bool
    on_click: Any
    on_change: Any
    on_input: Any
    on_submit: Any
    on_key_down: Any
    on_key_up: Any
    on_key_press: Any
    on_mouse_enter: Any
    on_mouse_leave: Any
    on_mouse_over: Any
    on_mouse_out: Any
    on_focus: Any
    on_blur: Any
    on_scroll: Any
    on_load: Any
    on_error: Any
    on_double_click: Any
    on_mouse_down: Any
    on_mouse_up: Any
    on_mouse_move: Any
    on_mouse_wheel: Any
    on_context_menu: Any
    on_drag: Any
    on_drag_start: Any
    on_drag_end: Any
    on_drag_over: Any
    on_drag_enter: Any
    on_drag_leave: Any
    on_drop: Any
    on_touch_start: Any
    on_touch_end: Any
    on_touch_move: Any
    on_touch_cancel: Any
    on_pointer_down: Any
    on_pointer_up: Any
    on_pointer_move: Any
    on_pointer_enter: Any
    on_pointer_leave: Any
    on_pointer_over: Any
    on_pointer_out: Any
    on_copy: Any
    on_cut: Any
    on_paste: Any
    on_focus_in: Any
    on_focus_out: Any
    on_wheel: Any
    on_animation_start: Any
    on_animation_end: Any
    on_animation_iteration: Any
    on_transition_end: Any
    on_submit_capture: Any
    on_change_capture: Any
    on_key_down_capture: Any
    on_key_up_capture: Any
    on_key_press_capture: Any
    on_mouse_enter_capture: Any
    on_mouse_leave_capture: Any
    on_focus_capture: Any
    on_blur_capture: Any
    on_load_capture: Any
    on_error_capture: Any
    on_input_capture: Any
    on_wheel_capture: Any
    fill: str
    stroke: str
    stroke_width: int | float | str
    stroke_linecap: str
    stroke_linejoin: str
    stroke_dasharray: str
    stroke_dashoffset: str
    stroke_miterlimit: int | float | str
    stroke_opacity: float | str
    fill_opacity: float | str
    opacity: float | str
    view_box: str
    preserve_aspect_ratio: str
    d: str
    cx: int | float | str
    cy: int | float | str
    r: int | float | str
    rx: int | float | str
    ry: int | float | str
    x: int | float | str
    y: int | float | str
    x1: int | float | str
    x2: int | float | str
    y1: int | float | str
    y2: int | float | str
    points: str
    path_length: int | float | str
    transform: str
    href_xlink: str
    clip_path: str
    mask: str
    filter: str
    xmlns: str
    xmlns_xlink: str
    gradient_units: str
    gradient_transform: str
    spread_method: str
    offset: str
    stop_color: str
    stop_opacity: float | str
    marker_start: str
    marker_mid: str
    marker_end: str
    dominant_baseline: str
    text_anchor: str
    alignment_baseline: str

Child = Node | str | int | float | bool | None | JSExpr

class TagCallable(Protocol):
    def __call__(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...

class H:
    def __call__(self, tag: Any, props: dict[str, Any] | None = None, *children: Child, **kwargs: Any) -> Node: ...
    def __getattr__(self, tag: str) -> TagCallable: ...

    def a(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def abbr(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def address(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def area(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def article(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def aside(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def audio(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def b(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def base(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def bdi(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def bdo(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def blockquote(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def body(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def br(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def button(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def canvas(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def caption(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def cite(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def code(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def col(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def colgroup(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def data(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def datalist(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def dd(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def details(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def dfn(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def dialog(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def div(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def dl(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def dt(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def em(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def embed(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def fieldset(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def figcaption(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def figure(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def footer(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def form(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def h1(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def h2(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def h3(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def h4(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def h5(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def h6(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def head(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def header(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def hgroup(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def hr(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def html(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def i(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def iframe(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def img(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def input(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def ins(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def kbd(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def label(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def legend(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def li(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def link(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def main(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def map(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def mark(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def menu(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def meta(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def meter(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def nav(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def noscript(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def object(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def ol(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def optgroup(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def option(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def output(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def p(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def param(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def picture(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def pre(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def progress(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def q(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def rp(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def rt(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def ruby(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def s(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def samp(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def script(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def search(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def section(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def select(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def slot(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def small(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def source(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def span(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def strong(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def style(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def sub(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def summary(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def sup(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def table(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def tbody(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def td(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def template(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def textarea(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def tfoot(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def th(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def thead(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def time(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def title(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def tr(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def track(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def u(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def ul(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def var(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def video(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def wbr(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def svg(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def g(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def defs(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def desc(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def title(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def symbol(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def use(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def image(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def path(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def rect(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def circle(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def ellipse(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def line(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def polyline(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def polygon(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def text(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def tspan(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def textPath(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def marker(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def pattern(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def mask(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def clipPath(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def linearGradient(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def radialGradient(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def stop(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def filter(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feBlend(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feColorMatrix(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feComponentTransfer(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feComposite(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feConvolveMatrix(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feDiffuseLighting(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feDisplacementMap(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feDistantLight(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feFlood(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feFuncA(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feFuncB(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feFuncG(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feFuncR(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feGaussianBlur(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feImage(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feMerge(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feMergeNode(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feMorphology(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feOffset(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def fePointLight(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feSpecularLighting(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feSpotLight(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feTile(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def feTurbulence(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...
    def foreignObject(self, *children: Child, **props: Unpack[HTMLProps]) -> Node: ...

h: H

__all__: list[str]
